# - name: Publish package to TestPyPI
#   uses: pypa/gh-action-pypi-publish@release/v1
#   with:
#     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#     repository_url: https://test.pypi.org/legacy/


# python3 -m pip install --upgrade pip
# python3 -m pip install --upgrade build
# python3 -m build
# python3 -m pip install --upgrade twine
# python3 -m twine upload --repository testpypi dist/*




name: Publish to PyPI
on:
  push:
    branches: [master]


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install build tools
        run: |
          python3 -m pip --upgrade pip
          python3 -m pip install build twine
          python3 -m pip --upgrade pip
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/